// Generated by CoffeeScript 1.7.1
(function() {
  var LivecriptCompiler, livescript, sysPath;

  livescript = require('livescript');

  sysPath = require('path');

  module.exports = LivecriptCompiler = (function() {
    LivecriptCompiler.prototype.brunchPlugin = true;

    LivecriptCompiler.prototype.type = 'javascript';

    LivecriptCompiler.prototype.extension = 'ls';

    function LivecriptCompiler(config) {
      this.config = config;
      null;
    }

    LivecriptCompiler.prototype.compile = function(data, path, callback) {
      var err, error, result;
      try {
        return result = livescript.compile(data, {
          bare: true,
          header: false
        });
      } catch (_error) {
        err = _error;
        return error = err;
      } finally {
        callback(error, result);
      }
    };

    return LivecriptCompiler;

  })();

}).call(this);
