// Generated by CoffeeScript 1.6.2
(function() {
  var LiveScript, LiveScriptCompiler, sysPath;

  LiveScript = require('LiveScript');

  sysPath = require('path');

  module.exports = LiveScriptCompiler = (function() {
    LiveScriptCompiler.prototype.brunchPlugin = true;

    LiveScriptCompiler.prototype.type = 'javascript';

    LiveScriptCompiler.prototype.extension = 'ls';

    function LiveScriptCompiler(config) {
      this.config = config;
      null;
    }

    LiveScriptCompiler.prototype.compile = function(data, path, callback) {
      var err, error, result;

      try {
        return result = LiveScript.compile(data, {
          bare: true
        });
      } catch (_error) {
        err = _error;
        return error = err;
      } finally {
        callback(error, result);
      }
    };

    LiveScriptCompiler.prototype.include = [sysPath.join(__dirname, '..', 'vendor', 'prelude-browser-0.6.0.js')];

    return LiveScriptCompiler;

  })();

}).call(this);
